inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - 'bin/*'
    - 'node_modules/**/*'
    - 'spec/**/*'
    - 'test/**/*'
    - 'db/migrate/**/*'
    - 'db/schema.rb'
  TargetRubyVersion: 2.5

Metrics/LineLength:
  Max: 120

FrozenStringLiteralComment:
  Enabled: false
Layout/EmptyLinesAroundClassBody:
  EnforcedStyle: empty_lines_except_namespace
Style/ClassAndModuleChildren:
  EnforcedStyle: nested
Style/Documentation:
  Enabled: false
