language: ruby
before_install:
  - gem install bundler
  - cp config/database.example.yml config/database.yml
bundler_args: --without production
cache: bundler
rvm:
  - 2.5
services:
  - postgresql
script:
  - bundle exec rails db:create
  - bundle exec rails db:migrate
  - bundle exec rspec
